package com.willianhdz.greendaogenerator.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.willianhdz.greendaogenerator.db.Articulos;

import com.willianhdz.greendaogenerator.db.ArticulosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articulosDaoConfig;

    private final ArticulosDao articulosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articulosDaoConfig = daoConfigMap.get(ArticulosDao.class).clone();
        articulosDaoConfig.initIdentityScope(type);

        articulosDao = new ArticulosDao(articulosDaoConfig, this);

        registerDao(Articulos.class, articulosDao);
    }
    
    public void clear() {
        articulosDaoConfig.clearIdentityScope();
    }

    public ArticulosDao getArticulosDao() {
        return articulosDao;
    }

}
